name: Deploy Shade Map to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install folium geopy numpy

    - name: Generate shade map
      run: python shade_map_visualizer.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages  # The branch the action should deploy to.
        keep_files: false  # Changed to false as we're deploying a single index.html file